---
title: "ETC5513 Assignment 2: A comprehensive Git, GitHub, and CLI  (Windows Terminal) Guide"
author: "Aditya Sharma"
format: html
---

## **1. Creating the project**

First, I created a new **RStudio Project** for the assignment. This keeps all files in one place and makes version control easier because the project folder becomes the working directory.

Inside the project, I created a simple "example.qmd" file and knitted it to HTML to confirm that the file works correctly. This step is important because it checks that the Quarto document renders before I start tracking changes with Git. And then I loaded my Assignment 1 dataset onto R.

```{r}
data <- read.csv("data/dataset.csv")
```

## **2. Initialising Git and connect GitHub**

Next, I opened the terminal in the project folder and initialised Git using the following commands:

``` bash
git init
```

This creates a local repository so Git can track my changes. I then added the files and made the first commit using commands:

``` bash
git add .
git commit -m "Initial commit with example qmd"
```

After that, I created a new repository on GitHub and linked it to my local project using commands:

``` bash
git remote add origin https://github.com/adityasharma0404/ETC5513-AdityaSharma-Assignment2.git

git branch -M main

git push -u origin main
```

This uploads the local repository to GitHub and sets "main" as the default branch.

## **3. Creating and using a branch**

I created a new branch called "testbranch" to work on changes separately from "main" using:

**- git checkout -b testbranch**

I then modified "example.qmd" on this branch and committed the change using commands:

**- git add example.qmd**

**- git commit -m "Update example qmd on testbranch"**

**- git push -u origin testbranch**

I have used a branching because it lets me work on new changes without affecting the main version of the project.

## **4. Adding the data folder and amend**

I created a folder called "data" and added the Assignment 1 dataset to it using the following commands:\

**- mkdir data**

**- cp "dataset" data/**

Then I staged the new folder and amended the previous commit so that the "data" folder became part of the last commit:
